/*
 *
 * Directory constants
 *
 */

export const SEARCH_DIRECTORY = 'app/Directory/SEARCH_DIRECTORY';
export const SEARCH_DIRECTORY_SUCCESS =
  'app/Directory/SEARCH_DIRECTORY_SUCCESS';
export const SEARCH_DIRECTORY_ERROR = 'app/Directory/SEARCH_DIRECTORY_ERROR';
export const SEARCH_DIRECTORY_MORE = 'app/Directory/SEARCH_DIRECTORY_MORE';
export const SEARCH_DIRECTORY_MORE_SUCCESS =
  'app/Directory/SEARCH_DIRECTORY_MORE_SUCCESS';
export const SEARCH_DIRECTORY_MORE_ERROR =
  'app/Directory/SEARCH_DIRECTORY_MORE_ERROR';
export const SUGGESTION = 'app/Directory/SUGGESTION';
export const SUGGESTION_SUCCESS = 'app/Directory/SUGGESTION_SUCCESS';
export const SUGGESTION_ERROR = 'app/Directory/SUGGESTION_ERROR';
export const SITE_FILTER_OPTIONS = 'app/Directory/SITE_FILTER_OPTIONS';
export const SITE_FILTER_OPTIONS_SUCCESS =
  'app/Directory/SITE_FILTER_OPTIONS_SUCCESS';
export const SITE_FILTER_OPTIONS_ERROR =
  'app/Directory/SITE_FILTER_OPTIONS_ERROR';
export const SERVICE_FILTER_OPTIONS = 'app/Directory/SERVICE_FILTER_OPTIONS';
export const SERVICE_FILTER_OPTIONS_SUCCESS =
  'app/Directory/SERVICE_FILTER_OPTIONS_SUCCESS';
export const SERVICE_FILTER_OPTIONS_ERROR =
  'app/Directory/SERVICE_FILTER_OPTIONS_ERROR';
export const HOBBY_FILTER_OPTIONS = 'app/Directory/HOBBY_FILTER_OPTIONS';
export const HOBBY_FILTER_OPTIONS_SUCCESS =
  'app/Directory/HOBBY_FILTER_OPTIONS_SUCCESS';
export const HOBBY_FILTER_OPTIONS_ERROR =
  'app/Directory/HOBBY_FILTER_OPTIONS_ERROR';
export const SKILL_FILTER_OPTIONS = 'app/Directory/SKILL_FILTER_OPTIONS';
export const SKILL_FILTER_OPTIONS_SUCCESS =
  'app/Directory/SKILL_FILTER_OPTIONS_SUCCESS';
export const SKILL_FILTER_OPTIONS_ERROR =
  'app/Directory/SKILL_FILTER_OPTIONS_ERROR';
export const VARIABLE_FILTER_OPTIONS = 'app/Directory/VARIABLE_FILTER_OPTIONS';
export const VARIABLE_FILTER_OPTIONS_SUCCESS =
  'app/Directory/VARIABLE_FILTER_OPTIONS_SUCCESS';
export const VARIABLE_FILTER_OPTIONS_ERROR =
  'app/Directory/VARIABLE_FILTER_OPTIONS_ERROR';
export const BADGE_FILTER_OPTIONS = 'app/Directory/BADGE_FILTER_OPTIONS';
export const BADGE_FILTER_OPTIONS_SUCCESS =
  'app/Directory/BADGE_FILTER_OPTIONS_SUCCESS';
export const BADGE_FILTER_OPTIONS_ERROR =
  'app/Directory/BADGE_FILTER_OPTIONS_ERROR';
