/*
 *
 * SessionsByOrigin constants
 *
 */

export const COUNT_COMMUNITY_MEMBER_CONNECTION =
  'app/SessionsByOrigin/COUNT_COMMUNITY_MEMBER_CONNECTION';
export const COUNT_COMMUNITY_MEMBER_CONNECTION_SUCCESS =
  'app/SessionsByOrigin/COUNT_COMMUNITY_MEMBER_CONNECTION_SUCCESS';
export const COUNT_COMMUNITY_MEMBER_CONNECTION_ERROR =
  'app/SessionsByOrigin/COUNT_COMMUNITY_MEMBER_CONNECTION_ERROR';
