/*
 *
 * Tab constants
 *
 */

export const GET_COMMUNITY_LIST = 'app/Tab/GET_COMMUNITY_LIST';
export const GET_COMMUNITY_LIST_SUCCESS = 'app/Tab/GET_COMMUNITY_LIST_SUCCESS';
export const GET_COMMUNITY_LIST_ERROR = 'app/Tab/GET_COMMUNITY_LIST_ERROR';
export const GET_COMMUNITY_TAB = 'app/Tab/GET_COMMUNITY_TAB';
export const GET_COMMUNITY_TAB_SUCCESS = 'app/Tab/GET_COMMUNITY_TAB_SUCCESS';
export const GET_COMMUNITY_TAB_ERROR = 'app/Tab/GET_COMMUNITY_TAB_ERROR';
export const GET_COMMUNITY_TAB_MORE = 'app/Tab/GET_COMMUNITY_TAB_MORE';
export const GET_COMMUNITY_TAB_MORE_SUCCESS =
  'app/Tab/GET_COMMUNITY_TAB_MORE_SUCCESS';
export const GET_COMMUNITY_TAB_MORE_ERROR =
  'app/Tab/GET_COMMUNITY_TAB_MORE_ERROR';
