/*
 *
 * Event constants
 *
 */

export const PARTICIPATE = 'app/Event/PARTICIPATE';
export const PARTICIPATE_SUCCESS = 'app/Event/PARTICIPATE_SUCCESS';
export const PARTICIPATE_ERROR = 'app/Event/PARTICIPATE_ERROR';
export const INTEGRATE = 'app/Event/INTEGRATE';
export const INTEGRATE_SUCCESS = 'app/Event/INTEGRATE_SUCCESS';
export const INTEGRATE_ERROR = 'app/Event/INTEGRATE_ERROR';
export const CANCEL_PARTICIPATION = 'app/Event/CANCEL_PARTICIPATION';
export const CANCEL_PARTICIPATION_SUCCESS =
  'app/Event/CANCEL_PARTICIPATION_SUCCESS';
export const CANCEL_PARTICIPATION_ERROR =
  'app/Event/CANCEL_PARTICIPATION_ERROR';
export const EXPORT_PARTICIPANTS = 'app/Event/EXPORT_PARTICIPANTS';
export const EXPORT_PARTICIPANTS_SUCCESS =
  'app/Event/EXPORT_PARTICIPANTS_SUCCESS';
export const EXPORT_PARTICIPANTS_ERROR = 'app/Event/EXPORT_PARTICIPANTS_ERROR';
export const STOP_PARTICIPATION = 'app/Event/STOP_PARTICIPATION';
export const STOP_PARTICIPATION_SUCCESS =
  'app/Event/STOP_PARTICIPATION_SUCCESS';
export const STOP_PARTICIPATION_ERROR = 'app/Event/STOP_PARTICIPATION_ERROR';
export const ADD_PARTICIPATION = 'app/Event/ADD_PARTICIPATION';
export const ADD_PARTICIPATION_SUCCESS = 'app/Event/ADD_PARTICIPATION_SUCCESS';
export const ADD_PARTICIPATION_ERROR = 'app/Event/ADD_PARTICIPATION_ERROR';
export const PARTICIPANTS = 'app/Event/PARTICIPANTS';
export const PARTICIPANTS_SUCCESS = 'app/Event/PARTICIPANTS_SUCCESS';
export const PARTICIPANTS_ERROR = 'app/Event/PARTICIPANTS_ERROR';
