/*
 *
 * UserDetails constants
 *
 */

export const LIST_USER_DETAILS_AND_ACTIONS =
  'app/UserDetails/LIST_USER_DETAILS_AND_ACTIONS';
export const LIST_USER_DETAILS_AND_ACTIONS_SUCCESS =
  'app/UserDetails/LIST_USER_DETAILS_AND_ACTIONS_SUCCESS';
export const TOTAL_CONNECT_AT_THE_MOMENT =
  'app/UserDetails/TOTAL_CONNECT_AT_THE_MOMENT';
export const TOTAL_CONNECT_AT_THE_MOMENT_SUCCESS =
  'app/UserDetails/TOTAL_CONNECT_AT_THE_MOMENT_SUCCESS';
export const VIEW_DETAILS = 'app/UserDetails/VIEW_DETAILS';
export const VIEW_DETAILS_SUCCESS = 'app/UserDetails/VIEW_DETAILS_SUCCESS';
export const VIEW_DETAILS_EXPORT = 'app/UserDetails/VIEW_DETAILS_EXPORT';
export const VIEW_DETAILS_EXPORT_SUCCESS =
  'app/UserDetails/VIEW_DETAILS_EXPORT_SUCCESS';
export const VIEW_DETAILS_EXPORT_ERROR =
  'app/UserDetails/VIEW_DETAILS_EXPORT_ERROR';
export const LIST_USER_NEVER_CONNECT =
  'app/UserDetails/LIST_USER_NEVER_CONNECT';
export const LIST_USER_NEVER_CONNECT_SUCCESS =
  'app/UserDetails/LIST_USER_NEVER_CONNECT_SUCCESS';
export const LIST_USER_CONNECT = 'app/UserDetails/LIST_USER_CONNECT';
export const LIST_USER_CONNECT_SUCCESS =
  'app/UserDetails/LIST_USER_CONNECT_SUCCESS';
export const LIST_USER_CONNECT_LESS_EQUAL_TEN_TIMES =
  'app/UserDetails/LIST_USER_CONNECT_LESS_EQUAL_TEN_TIMES';
export const LIST_USER_CONNECT_LESS_EQUAL_TEN_TIMES_SUCCESS =
  'app/UserDetails/LIST_USER_CONNECT_LESS_EQUAL_TEN_TIMES_SUCCESS';
export const LIST_USER_CONNECTION_SUMMARY =
  'app/UserDetails/LIST_USER_CONNECTION_SUMMARY';
export const LIST_USER_CONNECTION_SUMMARY_SUCCESS =
  'app/UserDetails/LIST_USER_CONNECTION_SUMMARY_SUCCESS';
export const USER_DETAILS_ERROR = 'app/UserDetails/USER_DETAILS_ERROR';
