/*
 *
 * GlobalContent constants
 *
 */

export const COUNT_CONTENT_CREATED_BY_DATE =
  'app/GlobalContent/COUNT_CONTENT_CREATED_BY_DATE';
export const COUNT_CONTENT_CREATED_BY_DATE_SUCCESS =
  'app/GlobalContent/COUNT_CONTENT_CREATED_BY_DATE_SUCCESS';
export const COUNT_CONTENT_CREATED_BY_DATE_ERROR =
  'app/GlobalContent/COUNT_CONTENT_CREATED_BY_DATE_ERROR';
