/*
 *
 * CommunityStatistics constants
 *
 */

export const COUNT_CONTENT_CREATED_BY_COMMUNITY =
  'app/CommunityStatistics/COUNT_CONTENT_CREATED_BY_COMMUNITY';
export const COUNT_CONTENT_CREATED_BY_COMMUNITY_SUCCESS =
  'app/CommunityStatistics/COUNT_CONTENT_CREATED_BY_COMMUNITY_SUCCESS';
export const COUNT_CONTENT_CREATED_BY_COMMUNITY_TABLE =
  'app/CommunityStatistics/COUNT_CONTENT_CREATED_BY_COMMUNITY_TABLE';
export const COUNT_CONTENT_CREATED_BY_COMMUNITY_TABLE_SUCCESS =
  'app/CommunityStatistics/COUNT_CONTENT_CREATED_BY_COMMUNITY_TABLE_SUCCESS';
export const ANALYZE_CONTENT_VIEWED_BY_COMMUNITY =
  'app/CommunityStatistics/ANALYZE_CONTENT_VIEWED_BY_COMMUNITY';
export const ANALYZE_CONTENT_VIEWED_BY_COMMUNITY_SUCCESS =
  'app/CommunityStatistics/ANALYZE_CONTENT_VIEWED_BY_COMMUNITY_SUCCESS';
export const ANALYZE_CONTENT_VIEWED_BY_COMMUNITY_TABLE =
  'app/CommunityStatistics/ANALYZE_CONTENT_VIEWED_BY_COMMUNITY_TABLE';
export const ANALYZE_CONTENT_VIEWED_BY_COMMUNITY_TABLE_SUCCESS =
  'app/CommunityStatistics/ANALYZE_CONTENT_VIEWED_BY_COMMUNITY_TABLE_SUCCESS';
export const VIEW_ACTIVITY_COMMUNITY =
  'app/CommunityStatistics/VIEW_ACTIVITY_COMMUNITY';
export const VIEW_ACTIVITY_COMMUNITY_SUCCESS =
  'app/CommunityStatistics/VIEW_ACTIVITY_COMMUNITY_SUCCESS';
export const COMMUNITY_STATISTICS_ERROR =
  'app/CommunityStatistics/COMMUNITY_STATISTICS_ERROR';
