/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CircularDependencyPlugin = require('circular-dependency-plugin');

module.exports = require('./webpack.base.babel')({
  mode: 'development',

  // Add hot reloading in development
  entry: {
    app: [
      require.resolve('react-app-polyfill/ie11'),
      'webpack-hot-middleware/client?reload=true',
      path.join(process.cwd(), 'app/app.js'), // Start with js/app.js
    ],
    'custom-tabs': [
      require.resolve('react-app-polyfill/ie11'),
      'webpack-hot-middleware/client?reload=true',
      path.join(process.cwd(), 'app/custom-tabs.js'), // Start with js/custom-tabs.js
    ],
    'onedrive_picker.html': [
      path.join(process.cwd(), 'app/onedrive_picker.js'),
    ],
  },

  // Don't use hashes in dev mode for better performance
  // please refer this https://github.com/wojtekmaj/react-pdf/issues/190
  // to know more about why globalobject set to this
  output: {
    filename: '[name].js',
    chunkFilename: '[name].chunk.js',
    globalObject: 'this',
  },

  // optimization: {
  //   splitChunks: {
  //     chunks: 'all',
  //   },
  // },

  // Add development plugins
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: 'app/index.html',
      filename: 'index.html',
      chunks: ['app'],
      // excludeChunks: ['custom-tabs'],
    }),
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: 'app/custom-tabs.html',
      filename: 'custom-tabs.html',
      chunks: ['custom-tabs'],
      // excludeChunks: ['app'],
    }),
    new HtmlWebpackPlugin({
      // inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: 'app/onedrive_picker.html',
      filename: 'onedrive_picker.html',
      chunks: ['onedrive_picker.html'],
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
  ],

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: 'eval-source-map',

  performance: {
    hints: false,
  },

  exclude: /node_modules\/(?!react-intl|intl-messageformat|@formatjs\/icu-messageformat-parser)/,
});
